### PR TITLE
Add script to check for gaps in taxonomic hierarchy.

### PR DESCRIPTION
**Pull request by egrace479**
This PR adds a script to check for gaps in the taxonomic hierarchy of our compiled dataset (i.e., following step 6 in the [create TreeOfLife10M instructions](https://github.com/Imageomics/open_clip/blob/main/docs/imageomics/treeoflife10m.md)). It prints warnings in the console indicating missing taxa.

There is a [test CSV](https://huggingface.co/datasets/imageomics/ToL-EDA/blob/main/data/tol_hierarchy_test.csv) in the [ToL-EDA HF repo](https://huggingface.co/datasets/imageomics/ToL-EDA).

Closes issue #11.

### CODE REVIEW

**Comment by egrace479** [comment]
Expected Test output:
```
WARNING:root:There are 4 kingdoms instead of 3.
WARNING:root:180 entries are missing rank kingdom, but have genus label.
WARNING:root:180 entries are missing rank phylum, but have genus label.
WARNING:root:313 entries are missing rank class, but have genus label.
WARNING:root:187 entries are missing rank order, but have genus label.
WARNING:root:180 entries are missing rank family, but have genus label.
WARNING:root:28 entries are missing rank class, but have family label.
WARNING:root:100 entries have kingdom and species labels but no genus.
WARNING:root:100 entries have phylum and species labels but no genus.
WARNING:root:73 entries have class and species labels but no genus.
WARNING:root:100 entries have order and species labels but no genus.
WARNING:root:100 entries have family and species labels but no genus.
WARNING:root:There are 180 samples for which the species column may have genus and species.
WARNING:root:10 species are labeled as '(unidentified)'.
```

**Comment by thompsonmj** [comment]
This is a good start for understanding where there are holes in the hierarchies, however it seems that the following may be more common than we originally thought:
- **Real holes:** Holes in the hierarchy where certain ranks are empty based on lack of consensus, e.g. no species in the class Solenogastres have the order rank specified in up-to-date authoritative naming sources.
- **Synonyms at lower ranks:** Similar to the Animalia/Metazoa issue, lower ranking taxa can use multiple terms for the same thing, and this might degrade performance.

If the HF test CSV can be located, I think we can call this good for now. 

We could talk over additional functionality to handle more powerful name / hierarchy resolution separately, e.g. using the [Global Names Verifier API](https://verifier.globalnames.org/api).

**Comment by egrace479** [comment]
> This is a good start for understanding where there are holes in the hierarchies, however it seems that the following may be more common than we originally thought:
> 
> * **Real holes:** Holes in the hierarchy where certain ranks are empty based on lack of consensus, e.g. no species in the class Solenogastres have the order rank specified in up-to-date authoritative naming sources.
> * **Synonyms at lower ranks:** Similar to the Animalia/Metazoa issue, lower ranking taxa can use multiple terms for the same thing, and this might degrade performance.
> 
> If the HF test CSV can be located, I think we can call this good for now.
> 
> We could talk over additional functionality to handle more powerful name / hierarchy resolution separately, e.g. using the [Global Names Verifier API](https://verifier.globalnames.org/api).

The link should work now.

Agreed. This would be part of the reason to manually run EDA to understand what is/isn't missing. 

Some potential solutions:
- If they are true holes, it should perhaps be filled with something like `unknown`? 
- We could also try to find synonyms by checking for duplicates of the 7-tuple taxa that have different values in the `common` column and similarly checking for duplicates of the 6-tuple (only down to `genus`) paired with `common` that have different `species` name (though this may be more commonly accurate).

**Review by samuelstevens — APPROVED** [review]
I ran it on the statistics.csv file for v3 and it correctly reported many issues (that I am now going to try and fix). I'm happy with it.

**Pull request merged**
