### PR TITLE
Fill out 7-rank hierarchy given messy genus and species terms.

### PR DESCRIPTION
**Pull request by thompsonmj**
Usage example:
```
python global_names_resolver.py <input path> <output path> --batch_size <batch number>
python global_names_resolver.py ../data/resolve-please.jsonl ../data/resolved.jsonl --batch_size 300
````

Known issues:
- Does not return results for all searches for various reasons
- Contains a mix of terms for various ranks, e.g. ...
    - Metazoa and Animalia
    - Chloroplastida and Plantae
    - Viridiplantae and Plantae
    - likely others

But it does fill out a good portion of the data.

Currently, it only uses results if the 7 desired ranks of `['kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species']` all exist in a source's result. Then it identifies the highest scoring source from these and returns the terms.

### CODE REVIEW

**Comment by thompsonmj** [comment]
Logging some manual checks ...
`{"genus": "Coprinopsis", "species": "lignicola rockefeller nom. prov."}

resolves to 

```
{
  "Coprinopsis lignicola rockefeller nom. prov.": {
    "National Center for Biotechnology Information": {
      "kingdom": "Fungi",
      "phylum": "Basidiomycota",
      "class": "Agaricomycetes",
      "order": "Agaricales",
      "family": "Psathyrellaceae",
      "genus": "Coprinopsis",
      "species": "Coprinopsis"
    }
  }
}
```

**Comment by thompsonmj** [comment]
✔
`{"genus": "Fragaria", "species": "orientalis losinsk."}`

resolves to 

```
{
  "Fragaria orientalis losinsk.": {
    "Catalogue of Life Checklist": {
      "kingdom": "Plantae",
      "phylum": "Tracheophyta",
      "class": "Magnoliopsida",
      "order": "Rosales",
      "family": "Rosaceae",
      "genus": "Fragaria",
      "species": "Fragaria orientalis"
    }
  }
}
```

**Comment by thompsonmj** [comment]
❌
`{"genus": "Eupithecia", "species": "analoga djakonov"}`

does not resolve, but searching for "Eupithecia analoga" returns good results on the website, though "Eupithecia analoga djakonov" does not.

**Comment by thompsonmj** [comment]
✔
`{"genus": "Arachnothera", "species": "longirostra flammifera tweeddale"}`

resolves to 

```
{
  "Arachnothera longirostra flammifera tweeddale": {
    "Catalogue of Life Checklist": {
      "kingdom": "Animalia",
      "phylum": "Chordata",
      "class": "Aves",
      "order": "Passeriformes",
      "family": "Nectariniidae",
      "genus": "Arachnothera",
      "species": "Arachnothera longirostra"
    }
  }
}
```

**Comment by thompsonmj** [comment]
`{"genus": "Cancellaria", "species": "haemastoma sowerby"}`

resolves to (and is corrected to!):

```
✔🌟
{
  "Cancellaria haemastoma sowerby": {
    "Catalogue of Life Checklist": {
      "kingdom": "Animalia",
      "phylum": "Mollusca",
      "class": "Gastropoda",
      "order": "Neogastropoda",
      "family": "Cancellariidae",
      "genus": "Bivetopsia",
      "species": "Bivetopsia haemastoma"
    }
  }
}
```

**Comment by egrace479** [comment]
Is this just a fix for the one file, or for overall usage?

**Comment by thompsonmj** [comment]
Can be used with any input JSONL file with lines formatted as:
```
{"genus": "Coprinopsis", "species": "lignicola rockefeller nom. prov."}
```

If more flexible input options are helpful those could be added subsequently as well. It's currently running on the 388,208 entries Sam shared.

**Review by egrace479 — APPROVED** [review]
LGTM

Though it adds even more kingdoms to the mix; taxonomy is interesting!

**Pull request merged**
